name: Parse and Upload Text File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC

jobs:
  parse_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python script 
        run: |
          python parse_text_file.py  # Ensure parse_text_file.py is your script
        
      - name: Commit and push changes (force commit)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Stage all files (including unchanged ones)
          git add --all
          
          # Force commit with a message to make sure files are always committed
          git commit -m "Update text file chunks, even if no changes were made" || echo "No changes to commit"
          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
